lib/insta_clone_web/router.ex
defmodule InstaCloneWeb.Router do
  use InstaCloneWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {InstaCloneWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug InstaCloneWeb.Plugs.Locale, "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InstaCloneWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/hello", HelloController, :index
    get "/hello/:messenger", HelloController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", InstaCloneWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: InstaCloneWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/tech_challenge_tradesquash_web/router.ex
defmodule TechChallengeTradesquashWeb.Router do
  use TechChallengeTradesquashWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TechChallengeTradesquashWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TechChallengeTradesquashWeb.Plugs.Locale, "en"
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :guardian do
    plug TechChallengeTradesquashWeb.Authentication.Pipeline
  end

  pipeline :browser_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", TechChallengeTradesquashWeb do
    pipe_through [:browser, :guardian, :browser_auth]

    # get "/", HomeController, :index
    resources "/profile", ProfileController, only: [:show], singleton: true

    resources "/posts", PostController do
      post "/comment", PostController, :add_comment
    end

    delete "/logout", SessionController, :delete
  end

  scope "/", TechChallengeTradesquashWeb do
    pipe_through [:browser]

    get "/", HomeController, :index
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", TechChallengeTradesquashWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TechChallengeTradesquashWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/tech_challenge_tradesquash_web/controllers/session_controller.ex
defmodule TechChallengeTradesquashWeb.SessionController do
  use TechChallengeTradesquashWeb, :controller
  alias TechChallengeTradesquash.Accounts
  alias TechChallengeTradesquashWeb.Authentication

  def new(conn, _params) do
    if Authentication.get_current_account(conn) do
      redirect(conn, to: Routes.post_path(conn, :index))
    else
      render(
        conn,
        :new,
        changeset: Accounts.change_account(),
        action: Routes.session_path(conn, :create)
      )
    end
  end

  def create(conn, %{"account" => %{"email" => email, "password" => password}}) do
    case email |> Accounts.get_by_email() |> Authentication.authenticate(password) do
      {:ok, account} ->
        conn
        |> Authentication.log_in(account)
        |> redirect(to: Routes.post_path(conn, :index))

      {:error, :invalid_credentials} ->
        conn
        |> put_flash(:error, "Incorrect email or password")
        |> new(%{})
    end
  end

  def delete(conn, _params) do
    conn
    |> Authentication.log_out()
    |> redirect(to: Routes.session_path(conn, :new))
  end
end

lib/tech_challenge_tradesquash_web/views/session_view.ex
defmodule TechChallengeTradesquashWeb.SessionView do
  use TechChallengeTradesquashWeb, :view
end

lib/tech_challenge_tradesquash_web/templates/session/new.html.heex
<div class="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div>
      <img class="mx-auto w-96" src="https://i.ibb.co/3FP6zzd/cover.png" alt="Workflow" />
    </div>
    <div class="row">
      <div class="column column-50 column-offset-25">
        <%= form_for @changeset, @action, [as: :account, class: "mt-8 space-y-6"], fn f -> %>
          <input type="hidden" name="remember" value="true" />
          <div class="rounded-md shadow-sm -space-y-px">
            <div>
              <%= label(f, :email, "Email address", class: "sr-only") %>
              <%= email_input(f, :email,
                type: "email",
                autocomplete: "email",
                required: true,
                placeholder: "Email address",
                class:
                  "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
              ) %>
              <%= error_tag(f, :email) %>
            </div>
            <div>
              <%= label(f, :password, "Password", class: "sr-only") %>
              <%= password_input(f, :password,
                required: true,
                placeholder: "Password",
                class:
                  "appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
              ) %>
              <%= error_tag(f, :password) %>
            </div>
          </div>

          <div>
            <%= submit("Log In",
              class:
                "group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            ) %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="mx-auto text-center">
      <%= link to: Routes.registration_path(@conn, :new) do %>
        <p class="text-gray-500 text-sm">
          Don't have account? <strong class="text-indigo-500">Sign up</strong>
        </p>
      <% end %>
    </div>
  </div>
</div>

lib/tech_challenge_tradesquash_web/templates/session/social_links.html.heex
<div class="social-log-in">
  <p>Or log in with</p>
  <%= link("Google", to: "#", class: "button button-outline") %>
  <%= link("Twitter", to: "#", class: "button button-outline") %>
</div>